spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.55.147.153:3306/blog?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
logging:
  level:
    root: info
    com.test: debug
  file:
    path: /root/blog
    name: spring.log
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.test.blog.pojo
server:
  port: 8081
