spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: pro

comment:
  avatar: /images/avatar.png
# about页面
about:
  qq: xx
  github: https://github.com/Q2035/blog
  wechat: 微信就算了

file:
  basePath: D:\temp\