spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: xxx
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
logging:
  level:
    root: warn
    com.test: debug
  file:
    path: D:/tmp/blog/
    name: log/blog-pro.lgo
server:
  port: 8081