spring:
  thymeleaf:
    mode: HTML
# 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xx:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: xx
    password: xx
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
  mvc:
    favicon:
      enabled: true
# Redis设置
  redis:
    host: xx
    port: 6379
    password: xx
    jedis:
      pool:
        max-wait: 3000 #连接池最大阻塞等待时间
        max-active: 100 #连接池最大连接数
        max-idle: 20 # 最大空闲连接
    timeout: 10000 # 连接超时
#  配置邮箱
  mail:
    host: smtp.qq.com
    username: xx
    password: xx
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 100MB

mailRecipient: 2383862181@qq.com

#日志
logging:
  level:
    root: warn
    com.test: info
  file:
    path: .
    name: log/blog-pro.log

#MyBatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.test.blog.pojo

#暴露的端口
server:
  port: xx
