spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx:3306/blog?useUnicode=true&characterEncoding=UTF-8
    username: xxx
    password: xxxx
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
#    tomcat:
#      time-between-eviction-runs-millis: 18800
#      test-while-idle: true
  mvc:
    favicon:
      enabled: true
  redis:
    host: xxx
    port: xxx
    password: xxx
    jedis:
      pool:
        max-wait: 3000 #连接池最大阻塞等待时间
        max-active: 100 #连接池最大连接数
        max-idle: 20 # 最大空闲连接
    timeout: 10000 # 连接超时
logging:
  level:
    root: warn
    com.test: info
  file:
    path: .
    name: log/blog-pro.log
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.test.blog.pojo
server:
  port: 8081
